import { useEffect, useState } from 'react';
import { motion, useScroll, useSpring } from 'motion/react';
import { ArrowDownRight, ArrowRight, Asterisk, Braces, CheckCircle2, Code2, Github, Linkedin, Mail, MapPin, MessageCircle, Palette, Sparkles, Terminal, Workflow } from 'lucide-react';
import Projects from './Projects';

const typedWords = ['produtos digitais.', 'automações inteligentes.', 'experiências visuais.', 'sistemas que trabalham.'];

function Typewriter(){const[word,setWord]=useState(0);const[count,setCount]=useState(0);const[deleting,setDeleting]=useState(false);useEffect(()=>{const current=typedWords[word];const finished=count===current.length;const empty=count===0;const wait=finished&&!deleting?1300:empty&&deleting?250:deleting?36:64;const timer=setTimeout(()=>{if(finished&&!deleting){setDeleting(true);return}if(empty&&deleting){setDeleting(false);setWord((word+1)%typedWords.length);return}setCount(count+(deleting?-1:1))},wait);return()=>clearTimeout(timer)},[word,count,deleting]);return <span className="typed-line">{typedWords[word].slice(0,count)}<i/></span>}

const tech = ['REACT','TYPESCRIPT','PYTHON','N8N','FASTAPI','REMOTION','SQL','POWER BI','FIGMA','DAVINCI RESOLVE'];
const services = [
  {icon:Code2,num:'01',title:'Produtos & sistemas',copy:'Apps, interfaces e painéis sob medida, construídos para fluxos reais de uso.'},
  {icon:Workflow,num:'02',title:'Automação & IA',copy:'Bots, integrações e pipelines que tiram o trabalho manual do caminho.'},
  {icon:Palette,num:'03',title:'Design & conteúdo',copy:'Identidade, campanhas, social e vídeo com direção visual consistente.'},
];

function Header({onDesign}:{onDesign:()=>void}){const[open,setOpen]=useState(false);const go=(id:string)=>{setOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};return <header className="site-header"><button className="site-logo" onClick={()=>go('home')}><span>DJA</span><i/></button><nav className={open?'open':''}>{[['about','Sobre'],['projects','Projetos'],['stack','Stack'],['contact','Contato']].map(([id,label])=><button onClick={()=>go(id)} key={id}>{label}</button>)}<button className="design-switch" onClick={onDesign}>Modo Design ↗</button></nav><div className="header-meta"><span><i/> ONLINE</span><button className="menu-toggle" onClick={()=>setOpen(!open)}>{open?'FECHAR':'MENU'}</button></div></header>}

function Hero(){return <section id="home" className="new-hero"><div className="hero-noise"/><div className="hero-topline"><span>PORTFOLIO / 2026</span><span>SALVADOR — BRASIL</span></div><div className="new-hero-core"><motion.div className="hero-badge" initial={{opacity:0,scale:.8}} animate={{opacity:1,scale:1}} transition={{delay:.2}}><Terminal/><span>HELLO, WORLD</span></motion.div><div className="glitch-wrap" data-text="DANIEL"><motion.h1 initial={{opacity:0,y:80}} animate={{opacity:1,y:0}} transition={{duration:.8,ease:[.16,1,.3,1]}}>DANIEL</motion.h1></div><div className="glitch-wrap outline" data-text="DE JESUS"><motion.h1 initial={{opacity:0,y:80}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:.08,ease:[.16,1,.3,1]}}>DE JESUS</motion.h1></div><div className="hero-typing"><span>EU CONSTRUO</span><Typewriter/></div><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.75}}>Desenvolvedor, criativo e construtor de produtos. Uno código, inteligência artificial e direção visual para transformar ideias em operações que funcionam.</motion.p><motion.div className="new-hero-actions" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.9}}><button onClick={()=>document.getElementById('projects')?.scrollIntoView({behavior:'smooth'})}>Explorar projetos <ArrowRight/></button><a href="mailto:contact@setupdja.website">Iniciar conversa <Mail/></a></motion.div></div><aside className="hero-system"><span>SYSTEM STATUS</span><div><b>CORE</b><i/><strong>READY</strong></div><div><b>IDEAS</b><i/><strong>ACTIVE</strong></div><div><b>COFFEE</b><i/><strong>98%</strong></div></aside><button className="hero-scroll" onClick={()=>document.getElementById('about')?.scrollIntoView({behavior:'smooth'})}><span>SCROLL</span><ArrowDownRight/></button></section>}

function About(){return <section id="about" className="new-about"><div className="about-index"><span>02</span><small>PROFILE.TXT</small></div><div className="about-lead"><span className="terminal-kicker">// quem está por trás</span><motion.h2 initial={{opacity:0,y:45}} whileInView={{opacity:1,y:0}} viewport={{once:true}}>Tecnologia com<br/><em>visão de negócio.</em></motion.h2><p>Não me interessa tecnologia pela tecnologia. Eu construo para reduzir passos, organizar operações e tornar ideias visíveis.</p></div><div className="about-details"><div className="terminal-window"><div className="terminal-bar"><span/><span/><span/><b>about_daniel.md</b></div><div className="terminal-content"><p><i>$</i> cat profile.md</p><p>Curso Análise e Desenvolvimento de Sistemas e atuo entre desenvolvimento, automação, dados e criação visual.</p><p>Minha experiência com atendimento, marketing e conteúdo trouxe algo importante para a técnica: clareza para conversar com clientes, senso de prazo e foco no resultado.</p><p>Uso IA como acelerador, com revisão, testes e decisão humana em cada entrega.</p><span className="terminal-cursor">_</span></div></div><div className="about-facts"><div><MapPin/><span>BASE</span><strong>Brasil</strong></div><div><Braces/><span>FOCO</span><strong>Produto digital</strong></div><div><Sparkles/><span>MÉTODO</span><strong>IA + critério</strong></div><div><CheckCircle2/><span>STATUS</span><strong>Disponível</strong></div></div></div></section>}

function Services(){return <section className="services-section"><div className="services-title"><span className="terminal-kicker">// o que eu faço</span><h2>Da estratégia<br/>à <em>execução.</em></h2></div><div className="services-list">{services.map((service,i)=><motion.article key={service.title} initial={{opacity:0,x:35}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.1}}><span>{service.num}</span><service.icon/><div><h3>{service.title}</h3><p>{service.copy}</p></div><ArrowRight/></motion.article>)}</div></section>}

function Stack(){return <section id="stack" className="new-stack"><div className="stack-heading"><span className="terminal-kicker">// capabilities.sys</span><h2>Ferramentas mudam.<br/><em>Capacidade fica.</em></h2><p>Uma stack híbrida para pensar, construir, automatizar e comunicar produtos completos.</p></div><div className="stack-terminal"><div className="terminal-bar"><span/><span/><span/><b>skills --list --verbose</b></div><div className="skill-command"><span>$</span><Typewriter/></div><div className="skill-columns"><div><small>DESENVOLVIMENTO</small><strong>React / TypeScript</strong><strong>Python / FastAPI</strong><strong>APIs / Integrações</strong></div><div><small>AUTOMAÇÃO & DADOS</small><strong>n8n / Workflows</strong><strong>SQL / Modelagem</strong><strong>Power BI</strong></div><div><small>CRIAÇÃO</small><strong>Figma / Photoshop</strong><strong>DaVinci / CapCut</strong><strong>Remotion / Motion</strong></div></div><div className="stack-footer"><span>12 MODULES LOADED</span><strong>NO ERRORS</strong></div></div></section>}

function Contact(){return <section id="contact" className="new-contact"><div className="contact-star"><Asterisk/></div><span className="terminal-kicker">// conexão aberta</span><h2>Tem um problema<br/>interessante?</h2><div className="contact-bottom"><p>Vamos transformar em um produto que funcione — e que tenha presença.</p><div className="contact-links"><a href="mailto:contact@setupdja.website"><Mail/> E-mail <ArrowRight/></a><a href="https://wa.me/5575982414860?text=Ol%C3%A1%20Daniel,%20vi%20seu%20portf%C3%B3lio%20e%20gostaria%20de%20conversar." target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp <ArrowRight/></a><a href="https://www.linkedin.com/in/daniel-de-jesus-00ab442b5/" target="_blank" rel="noreferrer"><Linkedin/> LinkedIn <ArrowRight/></a><a href="https://github.com/Dja-Cripto" target="_blank" rel="noreferrer"><Github/> GitHub <ArrowRight/></a></div></div></section>}

export default function RetroPortfolio({onDesign}:{onDesign:()=>void}){const{scrollYProgress}=useScroll();const scaleX=useSpring(scrollYProgress,{stiffness:100,damping:30,restDelta:.001});return <div className="retro-site"><motion.div className="progress-line" style={{scaleX}}/><div className="crt-overlay" aria-hidden="true"/><Header onDesign={onDesign}/><main><Hero/><div className="tech-marquee" aria-hidden="true"><div>{[...tech,...tech].map((item,i)=><span key={`${item}-${i}`}><Asterisk/>{item}</span>)}</div></div><About/><Services/><Projects/><Stack/><Contact/></main><footer className="new-footer"><span>DANIEL DE JESUS ALVES</span><span>DESENVOLVIDO COM CÓDIGO + IA</span><span>© {new Date().getFullYear()}</span></footer></div>}
