import { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion, useScroll, useSpring } from 'motion/react';
import { ArrowDownRight, ArrowRight, Asterisk, Award, Braces, BriefcaseBusiness, Check, CheckCircle2, Code2, Download, Github, GraduationCap, Linkedin, Mail, MapPin, MessageCircle, Palette, RotateCcw, Sparkles, Terminal, Workflow } from 'lucide-react';
import Projects from './Projects';

const typedWords = ['produtos digitais.', 'automações inteligentes.', 'painéis de dados.', 'sistemas que trabalham.'];

function Typewriter(){const[word,setWord]=useState(0);const[count,setCount]=useState(0);const[deleting,setDeleting]=useState(false);useEffect(()=>{const current=typedWords[word];const finished=count===current.length;const empty=count===0;const wait=finished&&!deleting?1300:empty&&deleting?250:deleting?36:64;const timer=setTimeout(()=>{if(finished&&!deleting){setDeleting(true);return}if(empty&&deleting){setDeleting(false);setWord((word+1)%typedWords.length);return}setCount(count+(deleting?-1:1))},wait);return()=>clearTimeout(timer)},[word,count,deleting]);return <span className="typed-line">{typedWords[word].slice(0,count)}<i/></span>}

function RetroCursor(){const dot=useRef<HTMLDivElement>(null);const ring=useRef<HTMLDivElement>(null);useEffect(()=>{const move=(event:MouseEvent)=>{if(dot.current)dot.current.style.transform=`translate3d(${event.clientX}px,${event.clientY}px,0)`;if(ring.current)ring.current.animate({transform:`translate3d(${event.clientX}px,${event.clientY}px,0)`},{duration:180,fill:'forwards'});const interactive=(event.target as HTMLElement).closest('a,button');ring.current?.classList.toggle('is-active',!!interactive)};const leave=()=>ring.current?.classList.add('is-hidden');const enter=()=>ring.current?.classList.remove('is-hidden');window.addEventListener('mousemove',move);document.addEventListener('mouseleave',leave);document.addEventListener('mouseenter',enter);return()=>{window.removeEventListener('mousemove',move);document.removeEventListener('mouseleave',leave);document.removeEventListener('mouseenter',enter)}},[]);return <><div ref={ring} className="retro-cursor-ring"/><div ref={dot} className="retro-cursor-dot"/></>}

const tech = ['REACT','TYPESCRIPT','PYTHON','N8N','FASTAPI','NEXT.JS','SQL','POWER BI','DOCKER','CLOUDFLARE'];
const services = [
  {icon:Code2,num:'01',title:'Produtos & sistemas',copy:'Apps, interfaces e painéis sob medida, construídos para fluxos reais de uso.'},
  {icon:Workflow,num:'02',title:'Automação & IA',copy:'Bots, integrações e pipelines que tiram o trabalho manual do caminho.'},
  {icon:Sparkles,num:'03',title:'Dados & inteligência',copy:'SQL, Power BI e IA aplicados a decisões claras e operações mais eficientes.'},
];

const experience = [
  { period: '2025', role: 'Auxiliar de Produção', company: 'Aceflex do Nordeste', detail: 'Operação em ambiente controlado, protocolos rigorosos e cooperação para cumprimento de metas.' },
  { period: '2024—25', role: 'Suporte Técnico', company: 'Atento', detail: 'Diagnóstico de hardware, software e redes, resolução de incidentes e orientação ao cliente.' },
  { period: '2020—22', role: 'Estoquista', company: 'Unidos Importados', detail: 'Controle de inventário em sistemas e coordenação do fluxo logístico interno.' },
  { period: '2018—19', role: 'Assistente Administrativo', company: 'CIEE / R L Campos', detail: 'Rotinas administrativas, documentos, lançamentos em sistemas e estruturação de cadastros.' },
];

const credentials = [
  ['Power BI', 'Business Intelligence & Data Science · 2026'],
  ['SQL', 'Análise de Dados · 72 horas'],
  ['Python', 'Fundamentos e aplicações de IA · 96 horas'],
  ['Dados', 'Formação profissional · 52 horas'],
  ['Excel', 'Avançado e produtividade · 60 horas'],
  ['n8n + IA', 'Automações e fluxos inteligentes · 2026'],
];

type BuildStatus='idle'|'processing'|'success'|'ready';
const buildSteps=[
  {prompt:'COMPLETE THE FLOW',nodes:['DATA',null,'OUTPUT'],options:['API','DATABASE','PROCESS'],correct:'PROCESS'},
  {prompt:'WHAT COMES NEXT?',nodes:['USER','UI',null,'DATABASE'],options:['API','SERVER','DESIGN'],correct:'API'},
];

function CodePlayground(){
  const[step,setStep]=useState(0);const[status,setStatus]=useState<BuildStatus>('idle');const[inserted,setInserted]=useState<string|null>(null);const[wrong,setWrong]=useState<string|null>(null);const timers=useRef<number[]>([]);const current=buildSteps[step];
  useEffect(()=>()=>timers.current.forEach(window.clearTimeout),[]);
  const choose=(option:string)=>{if(status!=='idle')return;if(option!==current.correct){setWrong(option);timers.current.push(window.setTimeout(()=>setWrong(null),650));return}setWrong(null);setInserted(option);setStatus('processing');timers.current.push(window.setTimeout(()=>setStatus('success'),1450));timers.current.push(window.setTimeout(()=>{if(step===buildSteps.length-1){setStatus('ready')}else{setStep(step+1);setInserted(null);setStatus('idle')}},2450))};
  const reset=()=>{timers.current.forEach(window.clearTimeout);timers.current=[];setStep(0);setStatus('idle');setInserted(null);setWrong(null)};
  const active=status==='processing'||status==='success';
  return <div className={`code-playground build-system ${status}`} aria-label="Build the System — experiência interativa"><div className="code-lab-bar"><span><i/> BUILD THE SYSTEM</span><small>{status==='ready'?'ONLINE':`STEP 0${step+1}/02`}</small></div><AnimatePresence mode="wait">{status==='ready'?<motion.div key="ready" className="system-ready" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}}><div className="ready-mark"><Check/></div><span>SYSTEM READY</span><div className="ready-list">{['DEVELOPMENT','AUTOMATION','DATA','DESIGN'].map(item=><div key={item}><b>{item}</b><Check/></div>)}</div><button onClick={()=>document.getElementById('projects')?.scrollIntoView({behavior:'smooth'})}>EXPLORE PROJECTS <ArrowRight/></button><button className="system-reset" onClick={reset}><RotateCcw/> RESTART SYSTEM</button></motion.div>:<motion.div key={step} className="build-stage" initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}}><div className="build-instruction"><strong>{current.prompt}</strong><span>Choose the missing piece</span></div><div className={`system-flow ${active?'active':''}`}>{current.nodes.map((node,index)=><div className="flow-part" key={`${step}-${index}`}>{index>0&&<div className="flow-line"><i/><i/><i/></div>}<motion.div className={`flow-node ${node?'':'missing'} ${!node&&inserted?'inserted':''}`} animate={!node&&inserted?{scale:[.78,1.08,1],boxShadow:['0 0 0 rgba(140,255,58,0)','0 0 28px rgba(140,255,58,.42)','0 0 10px rgba(140,255,58,.16)']}:undefined}>{node||inserted||'?'}</motion.div></div>)}</div><div className="piece-label">SELECT A MODULE</div><div className="build-options">{current.options.map(option=><motion.button key={option} onClick={()=>choose(option)} disabled={status!=='idle'} className={`${wrong===option?'wrong':''} ${inserted===option?'correct':''}`} animate={wrong===option?{x:[0,-5,5,-3,3,0]}:undefined}>{option}</motion.button>)}</div><div className="build-feedback" aria-live="polite">{wrong?<span className="try-again">MODULE INCOMPATIBLE · TRY AGAIN</span>:status==='processing'?<div className="processing-row"><span>PROCESSING...</span><div><motion.i initial={{width:0}} animate={{width:'100%'}} transition={{duration:1.25,ease:'linear'}}/></div><b>100%</b></div>:status==='success'?<motion.span className="complete-label" initial={{opacity:0,y:5}} animate={{opacity:1,y:0}}><Check/> SYSTEM COMPLETE</motion.span>:<span>SELECT ONE OPTION TO CONTINUE</span>}</div></motion.div>}</AnimatePresence></div>;
}

function Header({onDesign}:{onDesign:()=>void}){const[open,setOpen]=useState(false);const go=(id:string)=>{setOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})};return <header className="site-header"><button className="site-logo" onClick={()=>go('home')}><span>DJA</span><i/></button><nav className={open?'open':''}>{[['about','Sobre'],['career','Carreira'],['projects','Projetos'],['stack','Stack'],['contact','Contato']].map(([id,label])=><button onClick={()=>go(id)} key={id}>{label}</button>)}<button className="design-switch" onClick={onDesign}>Modo Design ↗</button></nav><div className="header-meta"><span><i/> OPEN TO WORK</span><button className="menu-toggle" onClick={()=>setOpen(!open)}>{open?'FECHAR':'MENU'}</button></div></header>}

function Hero({onDesign}:{onDesign:()=>void}){return <section id="home" className="new-hero"><div className="hero-noise"/><div className="hero-topline"><span>DESENVOLVIMENTO · DADOS · AUTOMAÇÃO</span><span>FEIRA DE SANTANA — BA</span></div><div className="new-hero-core"><motion.div className="hero-badge" initial={{opacity:0,scale:.8}} animate={{opacity:1,scale:1}} transition={{delay:.2}}><Terminal/><span>OPEN TO WORK</span></motion.div><div className="stable-title"><motion.h1 initial={{opacity:0,y:80}} animate={{opacity:1,y:0}} transition={{duration:.8,ease:[.16,1,.3,1]}}>DANIEL</motion.h1></div><div className="glitch-wrap outline" data-text="DE JESUS"><motion.h1 initial={{opacity:0,y:80}} animate={{opacity:1,y:0}} transition={{duration:.8,delay:.08,ease:[.16,1,.3,1]}}>DE JESUS</motion.h1></div><div className="hero-lower"><div className="hero-copy"><div className="hero-typing"><span>EU CONSTRUO</span><Typewriter/></div><motion.p initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.75}}>Desenvolvedor em formação, com base prática em suporte técnico, operações e processos. Uno código, inteligência artificial, automação e dados para transformar problemas reais em sistemas úteis.</motion.p><motion.div className="new-hero-actions" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.9}}><button onClick={()=>document.getElementById('projects')?.scrollIntoView({behavior:'smooth'})}>Explorar projetos <ArrowRight/></button><button className="mode-design-button" onClick={onDesign}>Modo Design <Palette/></button></motion.div></div><div className="hero-interactive"><CodePlayground/><aside className="hero-system"><span>CANDIDATE STATUS</span><div><b>ADS</b><i/><strong>CURSANDO</strong></div><div><b>ENGLISH</b><i/><strong>B1</strong></div><div><b>LOCATION</b><i/><strong>BA · BR</strong></div></aside></div></div></div><button className="hero-scroll" onClick={()=>document.getElementById('about')?.scrollIntoView({behavior:'smooth'})}><span>SCROLL</span><ArrowDownRight/></button></section>}

function About(){return <section id="about" className="new-about"><div className="about-index"><span>02</span><small>PROFILE.TXT</small></div><div className="about-lead"><span className="terminal-kicker">// quem está por trás</span><motion.h2 initial={{opacity:0,y:45}} whileInView={{opacity:1,y:0}} viewport={{once:true}}>Tecnologia com<br/><em>visão de negócio.</em></motion.h2><p>Não me interessa tecnologia pela tecnologia. Eu construo para reduzir passos, organizar operações e transformar informação em ação.</p></div><div className="about-details"><div className="terminal-window"><div className="terminal-bar"><span/><span/><span/><b>about_daniel.md</b></div><div className="terminal-content"><p><i>$</i> cat profile.md</p><p>Curso Análise e Desenvolvimento de Sistemas e atuo com desenvolvimento, automação, integrações e dados.</p><p>Minha experiência com atendimento, marketing e conteúdo trouxe algo importante para a técnica: clareza para conversar com clientes, senso de prazo e foco no resultado.</p><p>Uso IA como acelerador, com revisão, testes e decisão humana em cada entrega. O Modo Design será uma experiência separada, com identidade e projetos próprios.</p><span className="terminal-cursor">_</span></div></div><div className="about-facts"><div><MapPin/><span>BASE</span><strong>Brasil</strong></div><div><Braces/><span>FOCO</span><strong>Produto digital</strong></div><div><Sparkles/><span>MÉTODO</span><strong>IA + critério</strong></div><div><CheckCircle2/><span>STATUS</span><strong>Disponível</strong></div></div></div></section>}

function Services(){return <section className="services-section"><div className="services-title"><span className="terminal-kicker">// o que eu faço</span><h2>Da estratégia<br/>à <em>execução.</em></h2></div><div className="services-list">{services.map((service,i)=><motion.article key={service.title} initial={{opacity:0,x:35}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.1}}><span>{service.num}</span><service.icon/><div><h3>{service.title}</h3><p>{service.copy}</p></div><ArrowRight/></motion.article>)}</div></section>}

function Career(){return <section id="career" className="career-section"><header className="career-heading"><div><span className="terminal-kicker">// recruiter_view.exe</span><h2>Capacidade técnica.<br/><em>Experiência real.</em></h2></div><div className="recruiter-card"><span>RESUMO PARA RECRUTADORES</span><strong>ADS em andamento</strong><strong>Dados + BI + Automação</strong><strong>Inglês técnico intermediário</strong><a href="/curriculo-daniel-de-jesus-alves.pdf" download><Download/> Baixar currículo.pdf</a></div></header><div className="career-body"><div className="experience-track"><div className="track-head"><BriefcaseBusiness/><span>EXPERIÊNCIA PROFISSIONAL</span><i/></div>{experience.map((item,index)=><motion.article key={item.period} initial={{opacity:0,x:-24}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:index*.08}}><time>{item.period}</time><div><span>{item.company}</span><h3>{item.role}</h3><p>{item.detail}</p></div></motion.article>)}</div><aside className="credentials-panel"><div className="education-card"><GraduationCap/><span>FORMAÇÃO</span><h3>Análise e Desenvolvimento de Sistemas</h3><p>Graduação em andamento, com foco em engenharia de software, dados e inteligência artificial.</p></div><div className="cert-list"><div className="cert-head"><Award/><span>CERTIFICAÇÕES & FORMAÇÕES</span></div>{credentials.map(([name,detail])=><div key={name}><strong>{name}</strong><small>{detail}</small></div>)}</div></aside></div></section>}

function Stack(){return <section id="stack" className="new-stack"><div className="stack-heading"><span className="terminal-kicker">// capabilities.sys</span><h2>Ferramentas mudam.<br/><em>Capacidade fica.</em></h2><p>Uma stack técnica para pensar, construir, automatizar e sustentar produtos completos.</p></div><div className="stack-terminal"><div className="terminal-bar"><span/><span/><span/><b>skills --list --verbose</b></div><div className="skill-command"><span>$</span><Typewriter/></div><div className="skill-columns"><div><small>DESENVOLVIMENTO</small><strong>React / TypeScript</strong><strong>Python / FastAPI</strong><strong>APIs / Integrações</strong></div><div><small>AUTOMAÇÃO & DADOS</small><strong>n8n / Workflows</strong><strong>SQL / Modelagem</strong><strong>Power BI</strong></div><div><small>INFRA & INTELIGÊNCIA</small><strong>Docker / Cloudflare</strong><strong>IA aplicada a produto</strong><strong>Remotion / FFmpeg</strong></div></div><div className="stack-footer"><span>12 MODULES LOADED</span><strong>NO ERRORS</strong></div></div></section>}

function Contact(){return <section id="contact" className="new-contact"><div className="contact-star"><Asterisk/></div><span className="terminal-kicker">// conexão aberta</span><h2>Tem um problema<br/>interessante?</h2><div className="contact-bottom"><p>Vamos transformar em um produto que funcione — e que tenha presença.</p><div className="contact-links"><a href="mailto:contact@setupdja.website"><Mail/> E-mail <ArrowRight/></a><a href="https://wa.me/5575982414860?text=Ol%C3%A1%20Daniel,%20vi%20seu%20portf%C3%B3lio%20e%20gostaria%20de%20conversar." target="_blank" rel="noreferrer"><MessageCircle/> WhatsApp <ArrowRight/></a><a href="https://www.linkedin.com/in/daniel-de-jesus-00ab442b5/" target="_blank" rel="noreferrer"><Linkedin/> LinkedIn <ArrowRight/></a><a href="https://github.com/Dja-Cripto" target="_blank" rel="noreferrer"><Github/> GitHub <ArrowRight/></a></div></div></section>}

export default function RetroPortfolio({onDesign}:{onDesign:()=>void}){const{scrollYProgress}=useScroll();const scaleX=useSpring(scrollYProgress,{stiffness:100,damping:30,restDelta:.001});return <div className="retro-site"><RetroCursor/><motion.div className="progress-line" style={{scaleX}}/><div className="crt-overlay" aria-hidden="true"/><Header onDesign={onDesign}/><main><Hero onDesign={onDesign}/><div className="tech-marquee" aria-hidden="true"><div>{[...tech,...tech].map((item,i)=><span key={`${item}-${i}`}><Asterisk/>{item}</span>)}</div></div><About/><Services/><Career/><Projects/><Stack/><Contact/></main><footer className="new-footer"><span>DANIEL DE JESUS</span><span>DESENVOLVIDO COM CÓDIGO + IA</span><span>© {new Date().getFullYear()}</span></footer></div>}
